[31기 윤재웅]pairings 기능 구현
wecode-bootcamp-korea/31-2nd-OldVintage-frontend pull request #10
Opened 2022-04-19 05:59 UTC by JaySurplusYoon

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

![image](https://user-images.githubusercontent.com/24951988/163936040-0f419f1c-2aee-4481-acf7-4bfe4183eeab.png)

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 서버에서 받은 페어링 목록을 불러와 특정 위치에 표시한다. 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 서버에서 페어링 데이터 불러온 후 적절한 위치에 표시하기

2. 화면 사이즈에 따라 이미지 표시방식 변경(media query활용)
- 화면 `width` 480px미만시, 모바일로 가정하여 이미지 column방향으로 표시
- 화면 `width` 1024px미만시, 음식 이미지 사이즈 축소
- 화면  `width` 768미만시, 와인병 이미지 보여주지않기

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 미디어쿼리를 처음 사용해보았습니다. 화면축소에 따른 인터렉션 기준이 모호하여, 하기의 기준을 도입하여 진행하였습니다. 
![image](https://user-images.githubusercontent.com/24951988/163935880-31ee05ea-ee30-4d7b-868c-c43fac8879be.png)

<br />

## :: 기타 질문 및 특이 사항

2022-04-20 01:24 UTC, yeonuk-hwang requested changes
리뷰 확인 및 반영해주세요~!

2022-04-20 01:24 UTC, younuk23 commented on src/Pages/ProductDetail/Parings/Parings.js
> +              <img src={Object.values(pairing)} alt="음식종류이미지" />
Object.values 의 return 값은 array일텐데 src에 string이 아닌 array를 대입해도 잘 동작하나요?

2022-04-20 01:24 UTC, younuk23 commented on src/Pages/ProductDetail/Parings/Parings.js
> +  }
불필요해 보이네요!

2022-04-20 01:24 UTC, younuk23 commented on src/Pages/ProductDetail/ProductDetail.js
> +      {product.image !== '' && (
```suggestion
      {product.image && (
```
굳이 빈문자열이랑 비교할 필요가 없어보입니다!

2022-04-20 01:26 UTC, yeonuk-hwang commented
반응형 처리한 것 좋네요!! 그 중에서도 기준 찾아서 거기에 맞게 적용한 것 👍 👍

2022-04-20 04:36 UTC, JaySurplusYoon commented on src/Pages/ProductDetail/ProductDetail.js
> +      {product.image !== '' && (
넵 수정하였습니다 !

2022-04-20 04:37 UTC, JaySurplusYoon commented on src/Pages/ProductDetail/Parings/Parings.js
> +  }
제거하였습니다.

2022-04-20 04:40 UTC, JaySurplusYoon commented on src/Pages/ProductDetail/Parings/Parings.js
> +              <img src={Object.values(pairing)} alt="음식종류이미지" />
"pairings": [{"Pork": "https://i.ibb.co/HNt1LMX/image.png"}, {"Beef": "https://i.ibb.co/k29FKNk/image.png"}, {"Lamb": "https://i.ibb.co/xqy2Wdf/image.png"}, {"Mushroom": "https://i.ibb.co/6ybvhNG/image.png"}]

pairings라는 배열의 개별 객체인 pairingd을 map으로 하나씩 출력합니다. 이에  하나의 string이 return되고 있습니다.

2022-04-20 05:10 UTC, younuk23 commented on src/Pages/ProductDetail/Parings/Parings.js
> +              <img src={Object.values(pairing)} alt="음식종류이미지" />
논의 할 사항 남아있는 코멘트들은 resolve 누르시면 제가 확인을 못해서 누르시면 안됩니다! 해결하신 부분들만 resolve 해주세요!

2022-04-20 05:11 UTC, younuk23 commented on src/Pages/ProductDetail/Parings/Parings.js
> +              <img src={Object.values(pairing)} alt="음식종류이미지" />
MDN에서 찾아보시면 Object.values 메소드의 리턴값은 array 입니다.
그러면 재웅님이 의도하신대로 `"https://i.ibb.co/HNt1LMX/image.png"` 가 나오는 것이 아니라 `["https://i.ibb.co/HNt1LMX/image.png"]` 로 나오게 되어있습니다. 콘솔로 확인 한번 해보세요!

JSX 상에서 처리를 자동으로 해주는 것 같긴 하지만 명확하게 string을 src에 대입해주는게 좋아보이네요!

2022-04-20 05:18 UTC, younuk23 requested changes
리뷰 확인해주세요~!

2022-04-20 05:18 UTC, younuk23 commented on src/Pages/ProductDetail/ProductDetail.js
> +    fetch('http://10.58.2.57:8000/products/1')
api주소는 `config.js` 에서 관리하는 것으로 수정해주세요

API는 `config.js` 파일에서 일괄적으로 관리하면서 import, export 를 통해 사용하는 식으로 관리하는 것이 좋습니다. 그렇지 않을 경우, 백엔드 서버 IP 가 변경되면 fetch 함수를 일일이 찾아서 API 를 직접 수정해 주어야 하기 때문입니다.

아래는 config.js에서 API주소를 관리하는 하나의 예시입니다. 참고하셔서 팀원들과 논의 후 생각하신 방식으로 자유롭게 적용해주세요

```jsx
// src/config.js
const BASE_URL = 'http://10.58.5.151:8000'
const API = {
  product:`${BASE_URL}/products`,
  list:`${BASE_URL}/list`
}

// 사용하는 컴포넌트
import { API } from '../../../config.js';

...

fetch(`${API}/5`).then(...).then(...);
```

위의 경우, 백엔드 IP 가 바뀔 때 `config.js` 에서 IP 만 바꾸어주면 모든 API 가 새로운 IP 에 따라서 변경됩니다. 그렇기 때문에 일일이 fetch 함수를 찾아 API 를 수정해줄 필요가 없습니다.

2022-04-20 05:39 UTC, JaySurplusYoon commented on src/Pages/ProductDetail/ProductDetail.js
> +    fetch('http://10.58.2.57:8000/products/1')
말씀하신 BASEURL과 useParams를 사용하는 방식으로 수정하였습니다.

2022-04-20 05:42 UTC, JaySurplusYoon commented on src/Pages/ProductDetail/Parings/Parings.js
> +              <img src={Object.values(pairing)} alt="음식종류이미지" />
> MDN에서 찾아보시면 Object.values 메소드의 리턴값은 array 입니다. 그러면 재웅님이 의도하신대로 `"https://i.ibb.co/HNt1LMX/image.png"` 가 나오는 것이 아니라 `["https://i.ibb.co/HNt1LMX/image.png"]` 로 나오게 되어있습니다. 콘솔로 확인 한번 해보세요!
> 
> JSX 상에서 처리를 자동으로 해주는 것 같긴 하지만 명확하게 string을 src에 대입해주는게 좋아보이네요!

넵 console로 확인하니 말씀하신바와 같았습니다. 감사합니다.!
toString으로 형변환 수정하였습니다. 검토 요청드립니다.

2022-04-20 06:40 UTC, younuk23 commented
재웅님 푸쉬하시고 나면 & 다른 PR 머지되면 항상 컨플릭 있는지 확인해주세요! 컨플릭 해결해주세요!

2022-04-21 01:48 UTC, younuk23 approved these changes
LGTM

2022-04-21 01:49 UTC, merged