[31기 윤재웅]상세페이지 상단 제품요약 구현완료
wecode-bootcamp-korea/31-2nd-OldVintage-frontend pull request #4
Opened 2022-04-14 07:54 UTC by JaySurplusYoon

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상세페이지 레이아웃 및 데이터 수신 구현
- 제품 특성 태그 클릭시, 해당 태그 검색으로 연결기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
<상세페이지 구조도>
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/24951988/163337586-e68f9fd7-971d-4ce4-8a0f-3f5f4d8d96f1.png">

1. 제품상세정보 요약페이지`productDesc` 구현
 - `productDetail`에서 목데이터 상품정보 `fetch`-`GET`하여 state저장
 - `productDesc`에 제품정보, 와이너리, 명칭, 별점, 가격 정보 보여줌

2. 제품태그 링크 구현
- 특성태그를 map으로 렌더링하기위해, `productFeature' 선언 후 객체의 배열 형태로 데이터 대입. paring 특성은 push로 데이터 넣어줌.
- 데이터 형태는 `{key : value}`
- `useQueryString`이라는 customHook 선언하여, 데이터의 key값에 따라 서로 다른 쿼리파라미터 반환하게 함.
- `productFeature`컴포넌트에서 해당 태그 화면에 렌더링. 태그 클릭시 `useQueryString`으로 반환한 주소를 `Link to`에 넣어 이동할 수 있도록 함.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- Object.keys, Object.value 등 객체와 map의 올바른 활용방안에 대해 고민했습니다.
- 조건부 렌더링을 학습했습니다.

<br />

## :: 기타 질문 및 특이 사항
-Styled component과  Custom Hook의 위치와 사용방법이 적절한지 검토 요청드립니다.

2022-04-15 06:40 UTC, younuk23 requested changes
고생하셨습니다 재웅님 리뷰 확인 및 반영해주세요!

2022-04-15 06:40 UTC, younuk23 commented on src/Pages/ProductDetail/Component/ProductDesc/ProductDesc.js
> +    // acidic,
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2022-04-15 06:40 UTC, younuk23 commented on src/Pages/ProductDetail/Component/ProductDesc/ProductDesc.js
> +    { country: country },
key value가 동일한 이름이라면 단축속성명을 활용할 수 있습니다
```suggestion
    { country},
```

2022-04-15 06:40 UTC, younuk23 commented on src/Pages/ProductDetail/Component/ProductDesc/ProductDesc.js
> +
map은 새로운 배열을 만들기 위해서 사용하는 method입니다. 이경우 단순 loop를 돌기 위함이기 때문에 forEach가 좀 더 적절한 선택이겠네요

그리고, 기존 배열을 만들고 거기에 다른 요소들을 push 하는 과정을 거치는 것 보다 ~~~하게 생긴 배열을 만들것이다 라는 방식으로 코드를 짜는게 좀 더 읽는 사람이 이해하기 쉽습니다.
```jsx
const pairings = paring.map(item => ({paring: item}));
const productFeatures = [{winery},{grape}].concat(parings);
``` 
기존의 코드는 최종 결과를 파악하려면 productFeatures란 배열은 이렇게 생겼고, paring 배열의 map을 돌면서 하나하나 거기에 어떤 것을 만들어서 푸쉬를 한다라는 과정, 절차를 모두 이해해야합니다(절차적인 코드)

새롭게 리뷰드린 코드는 productFeatures의 최종 형태가 어떻게 생겼는지 바로 알 수 있습니다(선언적)

위 사항 한번 고민해보시고 앞으로 코드짤때도 적용해보시면 좋을 것 같네요!

2022-04-15 06:40 UTC, younuk23 commented on src/Pages/ProductDetail/Hooks/useQueryString.js
> +export default useQueryString;
- 함수 분리 👍
- 다만 useQueryString은 내부에서 useState, useEffect 등 다른 hook들을 쓰고 있지 않고 렌더링에 영향을 미치지 않네요, 이경우엔 hook으로 보기보다는 그냥 하나의 함수로 표현하는게 더 좋겠네요!
- 일반 함수로 생각하시고 네이밍 다시 수정해주시는게 좋겠네요 지금의 이름은 hook이라고 착각하기가 너무 쉬워보입니다!

2022-04-15 06:40 UTC, younuk23 commented on src/Pages/ProductDetail/Component/ProductDesc/ProductDesc.js
> +import theme from '../../../../style/Theme';
theme은 styled-components의 props으로 받아올 수 있으니 굳이 import할 필요는 없어보입니다!

2022-04-15 06:42 UTC, younuk23 commented
- 지금 만드신 useQueryString은 custom hook은 아닙니다! 혹시 이부분 차이점이 잘 이해가 안되시면 오셔서 질문주세요!
- styled components는 잘 사용하고 계시네요 다만, 일부 tag들 네스팅해서 그냥 쓰신 부분이 있는데 지금같은 경우에는 depth가 깊지 않아서 괜찮지만, 과도하고 nesting해서 쓰는 depth가 깊어지지 않도록 주의하는게 좋습니다!

2022-04-15 07:53 UTC, JaySurplusYoon commented on src/Pages/ProductDetail/Hooks/useQueryString.js
> +export default useQueryString;
customHook의 개념이 모호했는데 설명 감사드립니다 !근본적인 학습을 더 하겠습니다..

2022-04-15 08:09 UTC, JaySurplusYoon commented on src/Pages/ProductDetail/Component/ProductDesc/ProductDesc.js
> +import theme from '../../../../style/Theme';
수정하였습니다.

2022-04-15 08:26 UTC, JaySurplusYoon commented on src/Pages/ProductDetail/Component/ProductDesc/ProductDesc.js
> +    // acidic,
네 명심하겠습니다.. 감사합니다. 삭제하였습니다 !

2022-04-15 08:27 UTC, JaySurplusYoon commented on src/Pages/ProductDetail/Component/ProductDesc/ProductDesc.js
> +    { country: country },
반영하였습니다. 앞으로도 활용하겠습니다. 감사합니다.

2022-04-15 08:41 UTC, JaySurplusYoon commented on src/Pages/ProductDetail/Component/ProductDesc/ProductDesc.js
> +
선언적 코드의 컨셉 설명 감사드립니다.

해당사항 수정하였습니다.

2022-04-18 02:22 UTC, younuk23 commented
- 커밋 스쿼시해서 하나로 수정
- 컨플릭 해결
진행해주세요~!

2022-04-19 07:06 UTC, younuk23 approved these changes
LGTM 👍

2022-04-19 07:06 UTC, merged