[31기 전지현] ADD : ProductList 필터기능 1차완성
wecode-bootcamp-korea/31-2nd-OldVintage-frontend pull request #8
Opened 2022-04-17 06:24 UTC by TaxToCode

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 필터기능
- 무한스크롤

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 와인 리스트 필터기능, 무한스크롤 

1. 필터기능
* 사이드바 체크박스 클릭시 해당 쿼리가 적용된 상태로 다시 서버에서 데이터를 불러와서 랜더링합니다.
* 사이드바 체크박스, 가격 슬라이더, 우측상단 Sort 모두 작동하게 하였습니다.

2.무한스크롤
* 서드파티 라이브러리를 사용해서 구현하였습니다. (https://www.npmjs.com/package/react-infinite-scroll-component)

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
* 가격 슬라이더처럼 변화가 많은 경우에는 Debouncing을 해야 서버에 과부화를 주지 않는것을 알게 되었습니다.
* useEffect 관련해서 한박자 늦던 이유가 useEffect에 대한 개념이해가 잘못되었던것을 알게 되었습니다. 멘토님이 주신 글을 읽어보니 class형을 사용할때와 라이프사이클을 바라보는 관점이 달라야 한다는 것을 인지하였습니다.

<br />

## :: 기타 질문 및 특이 사항
- 쿼리로 limit을 5개씩 제한해서 불러오기 이전에 필터에 적합한 모든 와인의 갯수(예를 들면 20개)를 따로 불러와서 출력하고 싶은데 현재 구현구도에서는 그렇게 하기 위해선 20개 짜리 데이터를 불러와서 length에 대한 정보를 얻어야 합니다. 이러면 쿼리로 5개씩 받는 의미가 없어진다고 봐서 어떤 식으로 해결해야 할 지 궁금합니다.

2022-04-18 02:40 UTC, younuk23 requested changes
- 리뷰 확인 및 반영해주세요!
- 질문주신 사항은 limit, offset을 통해서 페이지네이션을 구현하는데, 구현하려면 전체 아이템의 갯수가 몇개인지 알아야함, 그런데 전체 아이템의 갯수를 알려면 전체 아이템을 다 불러와서 파악해야함, 이렇게 되면 페이지네이션을 통해서 필요한 요소들만 받아오는 이유가 없어짐
- 위 내용이 맞을까요?
- 위 내용이 맞다면 전체 아이템의 갯수는 클라이언트단에서 전체 아이템을 요청한뒤에 그 array의 length를 구하는식으로 구현하는 방식은 지현님이 말씀하신대로 비효율적이기에 권장되지 않습니다.
- 전체아이템의 갯수가 필요하다면 백엔드 API에 response값으로 total_item등 전체 아이템의 갯수를 같이 전달해달라고 요청 할 수 있겠네요!
- 백엔드분과 소통하면서 협의해서 한번 진행해보세요!

2022-04-18 02:40 UTC, younuk23 commented on src/Component/ProductList/ProductListCheckBox.js
> +  }, [setCheckBoxFilter]);
매 렌더링마다 effect가 발생할 것 같은데 의도하신 사항이 맞나요?

2022-04-18 02:40 UTC, younuk23 commented on src/Pages/ProductList/ProductList.js
> +  // ]);
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2022-04-18 02:40 UTC, younuk23 commented on src/Pages/ProductList/ProductList.js
> +  const [debouncedMinPrice, debouncedMaxPrice] = debouncedSliderFetchRequest;
state도 꽤나 많고 연관된 로직도 꽤나 많아서 한눈에 파악하기가 좀 어렵네요!
지금 당장 수정할 필요는 없지만, 추후 커스텀 훅을 통해서 연관된 기능끼리 분리하는것이 좋겠네요! 추후 도전과제로 진행해보세요!

2022-04-18 02:40 UTC, younuk23 commented on src/Pages/ProductList/hooks/useDebounce.js
> +export default useDebounce;
👍

2022-04-18 02:40 UTC, younuk23 commented on src/config.js
> +export default API;
👍

2022-04-18 06:14 UTC, TaxToCode commented on src/Component/ProductList/ProductListCheckBox.js
> +  }, [setCheckBoxFilter]);
의도하지 않은 상황이였습니다. 원래 의도는 의존성 배열안에 checkedInputs state가 있었어야 하는데 esLint 지적문제로 저렇게 했었습니다. 그래서 console.log로 체크해보니 너무 많은 연산이 되는거 같아서 고민하다가 useMemo를 이용해서 수정하니까 괜찮아진거 같습니다.

2022-04-18 06:14 UTC, TaxToCode commented on src/Pages/ProductList/ProductList.js
> +  // ]);
네 알겠습니다.

2022-04-18 06:14 UTC, TaxToCode commented on src/Pages/ProductList/ProductList.js
> +  const [debouncedMinPrice, debouncedMaxPrice] = debouncedSliderFetchRequest;
네 커스텀훅을 통해서 관심사 분리해서 작성하는것에 좀 더 신경쓰겠습니다.

2022-04-19 07:08 UTC, younuk23 approved these changes
LGTM 👍

2022-04-19 07:08 UTC, younuk23 commented on src/Component/ProductList/ProductListCheckBox.js
> +  ]);
함수를 메모라이징 할 때는, useMemo보다 useCallback 쓰시는게 좀 더 편리하게 할 수있습니다!

2022-04-19 07:08 UTC, merged